#!/bin/bash

# Copyright 2011 Matt Shannon

# This file is part of HTS-demo_CMU-ARCTIC-SLT-STRAIGHT-AR-decision-tree.
# See `License` for details of license and warranty.


set -e
set -u
set -o pipefail

cat "$@" | grep -v '\.state' | sed -r 's/^[^-]+-([^+]+)\+.*duration=([0-9]+).*$/\1 \2/' | awk 'BEGIN { count = 0 }; { prevCount = count; count += $2; print $1,$2,prevCount,count }'
